sonar.projectKey=libscientific

# Source and exclusion configuration
sonar.sources=src
sonar.exclusions=**/build/**,**/tests/**,docs/**,performance/**

# C/C++ Analysis (CFamily)
# Using the Generic Coverage format generated in the YML
sonar.coverageReportPaths=coverage-c.xml

# Python Analysis
sonar.python.version=3.12
sonar.python.coverage.reportPaths=src/python_bindings/coverage.xml

